### PR TITLE
Remove RuntimeEnvironment

### PR DESCRIPTION
**Pull request by BrennanConroy**
@anurse @pranavkm @pakrym

### CODE REVIEW

**Comment by anurse** [comment]
I'm going to ask the same questions I think I've asked you before just to make sure all our bases are covered :). You've checked with all partners who were using this and they're all ready to remove it right? Specifically NuGet and .NET CLI.

Looks good assuming those folks are all aware of the change.

**Comment by pranavkm** [comment]
@anurse - they could continue using RC2 builds of this package until they migrate to RuntimeInformation.

**Comment by BrennanConroy** [comment]
NuGet has already removed the reference, and the CLI was getting it from NuGet so they will be removing it from their side too. Those are the only teams I could find that had a reference to it

**Comment by pranavkm** [comment]
:shipit:

**Comment by anurse** [comment]
:shipit: and don't forget to write an announcement

**Comment by anurse** [comment]
> they could continue using RC2 builds of this package until they migrate to RuntimeInformation.

Of course. I just wanted to make sure they were in the loop :)

**Pull request merged**
