### PR TITLE
Remove IRuntimeEnvironment.RuntimePath

### LINKED ISSUE #29: Remove private reflection for Assembly.Location in netstandard1.3
Assembly.Location is only available in netstandard1.5 which would require us to retarget PlatformAbstractions. We could consider removing the API (doesn't seem like anybody uses it) or target netstandard1.5

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #29

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @davidfowl \ @anurse

**Comment by Eilon** [comment]
:shipit:

**Comment by davidfowl** [comment]
I think this breaks the error page but I can't remember :shipit:

**Comment by Eilon** [comment]
Doesn't seem to be used in Diagnostics repo as far as I can tell.

**Comment by pranavkm** [comment]
I couldn't find any references to this in our codebase. I'll check this in this evening to avoid causing randomization on the CI in case this is a breaking change.

**Pull request closed without merging**
