### PR TITLE
Some clean-up in platform abstractions

### PR DESCRIPTION
**Pull request by henkmollema**
- Add missing license headers
- Remove unnecessary usings
- Add new lines at end of file

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Can you please make this PR against the Release branch? We're using Release for the dotnet work

**Comment by davidfowl** [comment]
@victorhurdugaci This is the problem with 2 branches.

**Comment by henkmollema** [comment]
@victorhurdugaci which Release branch? Do you mean master? Nice santa hat btw :santa:

**Comment by victorhurdugaci** [comment]
Ugh, hold on, we forgot to branch this repo. cc @anurse @pranavkm

**Comment by victorhurdugaci** [comment]
Thanks :)

**Comment by anurse** [comment]
Right now all PlatformAbstractions work is being done in `dev` because it's a new repo.

**Comment by victorhurdugaci** [comment]
We need it in the release feed :)

**Comment by pranavkm** [comment]
Oops. It's not listed in Universe so the build script did not branch it. Go ahead and `git checkout dev -b release` and update the `NuGet.config` to point to aspnetcirelease.

**Comment by anurse** [comment]
Created a `release` branch. @henkmollema can you rebase on that and open a new PR? Then I think we can merge it :)

**Pull request closed without merging**
