### PR TITLE
Migrate to using System.Runtime.Loader.AssemblyLoadContext

### PR DESCRIPTION
**Pull request by pakrym**
aspnet/dnx#3227
@davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
@pakrym Make sure you add an announcement for this.

**Comment by davidfowl** [comment]
It'll also break DNX so fix it there too.

**Comment by davidfowl** [comment]
We can't move ILibrarayMangar yet.  There's no replacement that works on both DNX and cli.

**Comment by pakrym** [comment]
Let people reference PlatformAbstractions.Dnx and use library manager from it

**Pull request merged**
