### PR TITLE
Add AppVeyor badge

### PR DESCRIPTION
**Pull request by henkmollema**
Use `dev` branch for Travis badge as well.

### CODE REVIEW

**Comment by henkmollema** [comment]
@Eilon are you sure the badge ID `m1ax1q33swwyaidm` is correct? I'm getting: 
```json
{"message":"Build not found or access denied."}
```

**Comment by anurse** [comment]
Looks good, but I'd rather not merge it until we know why the badge is failing. It could just be because we haven't made any changes in dev since AppVeyor was activated. There are some PRs that will land today so if that is the problem it should be fixed soon and I'll merge then :)

**Comment by anurse** [comment]
Yep, it was as I expected. Merging now!

**Comment by henkmollema** [comment]
Yay :smile:

**Pull request merged**
