### PR TITLE
Some clean-up in platform abstractions

### PR DESCRIPTION
**Pull request by henkmollema**
- Add missing license headers
- Remove unnecessary usings
- Add new lines at end of file

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Looks pretty straighforward to me, :shipit: from me . I'll let @anurse sign off and merge

**Comment by anurse** [comment]
I'll merge. The build is failing because the other PR that adds a travis.yml hasn't been merged so Travis is trying to build with `rake` :)

**Comment by csunali** [comment]
Excuse my ignorance but what is the purpose of "Add new lines at end of file"?

I see that it is automatically added to every file within VS while creating one. I thought it was something to remain from those c, c++ times.

Do we have some reason of having it in C# files?

Thanks!

**Pull request merged**
